### ISSUE TITLE
Failed to parse warning example error.

### ISSUE THREAD

**Issue by CrowdHailer** [jeremyjh/dialyxir#237] opened 2018-08-24 14:26 UTC
Hi I have a dialyzer warning that cannot be parsed by dialyxir. I think it's something to do with anonymous functions.

I have opened a PR on my project with the smallest changes needed to trigger the warning. 
https://github.com/CrowdHailer/OK/pull/54

**Comment by asummers** [comment] 2018-08-24 14:30
Hi @CrowdHailer thanks for the report and the project test case! That's super helpful. This is a duplicate of #234 (it's the whens in the `@spec`) and should be resolved in a few days! Going to close this for now, and I'll shoot you a ping when it's all merged into master.

**Closed by asummers** 2018-08-24 14:30 UTC

**Comment by CrowdHailer** [comment] 2018-08-24 14:35
Thanks. Now I just need to work out how to solve the actual warning
