### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by ConnorRigby** [jeremyjh/dialyxir#244] opened 2018-09-13 15:29 UTC
```
lib/nerves_time/ntpd.ex:69:pattern_match_cov
The pattern
:variable_

can never match since previous clauses completely cover the type
nil
________________________________________________________________________________
Please file a bug in https://github.com/jeremyjh/dialyxir/issues with this message.

Failed to parse warning:
[{:"(", 1}, {:atom_part, 1, 'P'}, {:atom_part, 1, 'o'}, {:atom_part, 1, 'r'}, {:atom_part, 1, 't'}, {:atom_part, 1, 'N'}, {:atom_part, 1, 'a'}, {:atom_part, 1, 'm'}, {:atom_part, 1, 'e'}, {:",", 1}, {:atom_part, 1, 'P'}, {:atom_part, 1, 'o'}, {:atom_part, 1, 'r'}, {:atom_part, 1, 't'}, {:atom_part, 1, 'S'}, {:atom_part, 1, 'e'}, {:atom_part, 1, 't'}, {:atom_part, 1, 't'}, {:atom_part, 1, 'i'}, {:atom_part, 1, 'n'}, {:atom_part, 1, 'g'}, {:atom_part, 1, 's'}, {:")", 1}, {:->, 1}, {:atom_part, 1, 'p'}, {:atom_part, 1, 'o'}, {:atom_part, 1, 'r'}, {:atom_part, 1, 't'}, {:"(", 1}, {:")", 1}, {:atom_part, 1, 'w'}, {:atom_part, 1, 'h'}, {:atom_part, 1, 'e'}, {:atom_part, 1, 'n'}, {:atom_part, 1, 'P'}, {:atom_part, 1, 'o'}, {:atom_part, 1, 'r'}, {:atom_part, 1, 't'}, {:atom_part, 1, 'N'}, {:atom_part, 1, 'a'}, {:atom_part, 1, 'm'}, {:atom_part, 1, 'e'}, {:::, 1}, {:"{", 1}, {:atom_full, 1, '\'spawn\''}, {:",", 1}, {:atom_part, 1, 'C'}, {:atom_part, 1, ...}, {:atom_part, ...}, {...}, ...]


Legacy warning:
lib/nerves_time/ntpd.ex:154: The call erlang:open_port({'spawn_executable',binary()},['binary' | 'exit_status' | 'stderr_to_stdout' | 'use_stdio' | {'args',[any(),...]} | {'line',2048},...]) breaks the contract (PortName,PortSettings) -> port() when PortName :: {'spawn',Command::string() | binary()} | {'spawn_driver',Command::string() | binary()} | {'spawn_executable',FileName::file:name()} | {'fd',In::non_neg_integer(),Out::non_neg_integer()}, PortSettings :: [Opt], Opt :: {'packet',N::1 | 2 | 4} | 'stream' | {'line',L::non_neg_integer()} | {'cd',Dir::string() | binary()} | {'env',Env::[{Name::os:env_var_name(),Val::os:env_var_value() | 'false'}]} | {'args',[string() | binary()]} | {'arg0',string() | binary()} | 'exit_status' | 'use_stdio' | 'nouse_stdio' | 'stderr_to_stdout' | 'in' | 'out' | 'binary' | 'eof' | {'parallelism',Boolean::boolean()} | 'hide'
```

**Comment by ConnorRigby** [comment] 2018-09-13 18:14
Also For what it's worth the issue was `{'spawn_executable',binary()}` Port.open is speced to take `{:spawn_executable, charlist}`

**Comment by asummers** [comment] 2018-09-14 14:07
Interesting. I think this is a duplicate of https://github.com/asummers/erlex/issues/16 but the one argument variant, not the multihead variant. 

@ConnorRigby can you do me a favor and tell me if your spec has a `when` clause? It looks like it does, but just want to confirm. If so, if you wouldn't mind also removing that when clause, putting the incorrect type spec back, then rerunning dialyzer and telling me if it succeeds?

I'm _pretty_ sure specs with whens are just completely broken currently and that's a bad bug.

**Comment by ConnorRigby** [comment] 2018-09-14 14:14
[here](https://github.com/fhunleth/nerves_time/blob/master/lib/nerves_time/ntpd.ex#L144) is the function failing

and [here](https://github.com/fhunleth/nerves_time/blob/master/lib/nerves_time/ntpd.ex#L154) is the fixed code.

MuonTrap.muontrap_path() is a binary. this is what the code looked like previously.

```
    Port.open({:spawn_executable, MuonTrap.muontrap_path()}, [
      {:args, ["--" | args]},
      :exit_status,
      :use_stdio,
      :binary,
      {:line, 2048},
      :stderr_to_stdout
    ])
```

I _think_ this was a bug in the `Port.open/2` spec. I had a look through 
git history on elixir-lang/elixir, but couldn't find anything useful because 
they refactored the entire file recently.,

**Comment by asummers** [comment] 2018-09-14 14:38
Ha so this was fun.

https://github.com/elixir-lang/elixir/blob/v1.7.3/lib/elixir/lib/port.ex#L180 calls into Erlang, so we find that function:

https://github.com/erlang/otp/blob/7b206e455df25a8e4ae78cae1939748ed693be40/erts/preloaded/src/erlang.erl#L2184

which _does_ have a `when` in the spec. So that confirms my theory.

**Closed** 2018-09-18 13:53 UTC
