### ISSUE TITLE
Dialyxir doesn't check code in test directory

### ISSUE THREAD

**Issue by dylan-chong** [jeremyjh/dialyxir#86] opened 2017-04-07 00:45 UTC
```
  @spec y() :: any
  def y() do
    x('a') # should be a number
  end

  @spec x(number) :: any
  def x(t) do
  end
```

Put the above code in a test file of a mix project and run `mix dialyzer`. It will succeed. If you move the above code into a file inside `lib`, it will fail (as expected). It would be very useful for dialyzer to check tests as well.

**Comment by jeremyjh** [comment] 2017-04-07 00:54
It would be nice, but presently it is out of scope. 

The issue is, that Dialyzer is an Erlang tool which does not know anything about Elixir. It can however check compiled BEAM files. Mix tests are in script files (.exs) and these are not compiled to BEAM modules.

It is possible to check your tests, if you reconfigure your mix project to compile the tests. See this [article](http://learningelixir.joekain.com/dialyzer-and-integration-tests/) for a description of how to do it, and the comments at the bottom for potentially better solution. I think it would be nice to have better tooling for this and I'd welcome someone interested in building that in `dialyxir`  but I'm not able to take it on this project right now.

**Closed by jeremyjh** 2017-04-07 00:54 UTC
