### ISSUE TITLE
FunctionClauseError when launching mix.dialyzer.plt

### ISSUE THREAD

**Issue by Annwenn** [jeremyjh/dialyxir#30] opened 2015-09-23 22:27 UTC
```Shell
uniaika 00:24 (master ) ~/repos/Repox/dialyxir ❯❯ mix dialyzer.plt
Starting PLT Core Build ... this will take awhile
dialyzer --output_plt /home/uniaika/.dialyxir_core_18_1.0.5.plt --build_plt --apps erts kernel stdlib crypto public_key -r /usr/lib64/elixir/bin/../lib/elixir/../eex/ebin /usr/lib64/elixir/bin/../lib/elixir/../elixir/ebin /usr/lib64/elixir/bin/../lib/elixir/../ex_unit/ebin /usr/lib64/elixir/bin/../lib/elixir/../iex/ebin /usr/lib64/elixir/bin/../lib/elixir/../mix/ebin
  Compiling some key modules to native code...{"init terminating in do_boot",{{badmatch,ok},[{dialyzer_cl,hc_cache,1,[{file,"dialyzer_cl.erl"},{line,573}]},{lists,foreach,2,[{file,"lists.erl"},{line,1337}]},{dialyzer_cl,hipe_compile,2,[{file,"dialyzer_cl.erl"},{line,517}]},{dialyzer_cl,do_analysis,4,[{file,"dialyzer_cl.erl"},{line,383}]},{dialyzer,'-cl/1-fun-0-',1,[{file,"dialyzer.erl"},{line,153}]},{dialyzer,doit,1,[{file,"dialyzer.erl"},{line,243}]},{dialyzer,plain_cl,0,[{file,"dialyzer.erl"},{line,84}]},{init,start_it,1,[]}]}}

** (FunctionClauseError) no function clause matching in Keyword.get/3
    (elixir) lib/keyword.ex:118: Keyword.get(:no_such_file, :files, nil)
    lib/mix/tasks/dialyzer.plt.ex:132: Mix.Tasks.Dialyzer.Plt.core_plt_contains?/2
    lib/mix/tasks/dialyzer.plt.ex:123: anonymous fn/1 in Mix.Tasks.Dialyzer.Plt.missing_apps/0
    (elixir) lib/enum.ex:662: anonymous fn/3 in Enum.filter/2
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:662: Enum.filter/2
    lib/mix/tasks/dialyzer.plt.ex:106: Mix.Tasks.Dialyzer.Plt.need_add?/0
    lib/mix/tasks/dialyzer.plt.ex:57: Mix.Tasks.Dialyzer.Plt.run/1
```

**Comment by totallymike** [comment] 2015-09-24 02:46
Just ran into the same thing

**Comment by jeremyjh** [comment] 2015-09-24 11:39
Hi, If you check closed tickets you will see the explanation - Elixir does
not support Erlang 18

**Comment by fishcakez** [comment] 2015-10-21 14:38
Elixir supports Erlang/OTP 18 from v1.0.5.

Elixir 1.2 will drop support for Erlang/OTP 17.

**Comment by cgarciae** [comment] 2015-10-22 16:35
Same problem. Is there a work around?

**Comment by antage** [comment] 2015-11-02 10:26
Same problem with Elixir 1.1 and Erlang 18.

**Comment by antage** [comment] 2015-11-07 21:20
I did rebuild Elixir with Erlang 18 and the problem is gone. I think the issue is because Elixir was built with Erlang 17 but dialyzer runs on Erlang 18.

**Comment by jeremyjh** [comment] 2015-11-11 17:24
@cgarciae @totallymike @Annwenn  - any chance any of you can confirm @antage 's workaround ?

**Comment by cgarciae** [comment] 2015-11-11 17:32
@antage How did you rebuild elixir?

**Comment by fishcakez** [comment] 2015-11-11 18:11
If Elixir is compiled using OTP 17.0 and dialyzer is run using OTP 18.0 then dialyzer will crash. The same for the reverse way around. The Erlang AST changed incompatibly for map `@spec` between those versions.

**Comment by antage** [comment] 2015-11-11 18:59
@cgarciae I took https://packages.debian.org/source/stretch/elixir-lang and rebuild (`dpkg-source -x`, `dpkg-buildpackage -us -us`) against erlang 18.

**Comment by sdwolf** [comment] 2015-11-24 20:14
I can also confirm this.
I installed elixir from sources with erlang 18.1 using this Dockerfile: https://github.com/sdwolf/dockerfiles/blob/master/elixir/Dockerfile

This is the output that I got:
```
notroot@6c086fe12b82:/work$ mix dialyzer.plt
Starting PLT Core Build ... this will take awhile
dialyzer --output_plt /home/notroot/.dialyxir_core_18_1.1.1.plt --build_plt --apps erts kernel stdlib crypto public_key -r /usr/local/lib/elixir/bin/../lib/elixir/../eex/ebin /usr/local/lib/elixir/bin/../lib/elixir/../elixir/ebin /usr/local/lib/elixir/bin/../lib/elixir/../ex_unit/ebin /usr/local/lib/elixir/bin/../lib/elixir/../iex/ebin /usr/local/lib/elixir/bin/../lib/elixir/../mix/ebin
  Compiling some key modules to native code... done in 0m40.33s
  Creating PLT /home/notroot/.dialyxir_core_18_1.1.1.plt ...
Unknown functions:
  'Elixir.Collectable.Atom':'__impl__'/1
  'Elixir.Collectable.Float':'__impl__'/1
  'Elixir.Collectable.Function':'__impl__'/1
  'Elixir.Collectable.Integer':'__impl__'/1
  'Elixir.Collectable.PID':'__impl__'/1
  'Elixir.Collectable.Port':'__impl__'/1
  'Elixir.Collectable.Reference':'__impl__'/1
  'Elixir.Collectable.Tuple':'__impl__'/1
  'Elixir.Enumerable.Atom':'__impl__'/1
  'Elixir.Enumerable.BitString':'__impl__'/1
  'Elixir.Enumerable.Float':'__impl__'/1
  'Elixir.Enumerable.Integer':'__impl__'/1
  'Elixir.Enumerable.PID':'__impl__'/1
  'Elixir.Enumerable.Port':'__impl__'/1
  'Elixir.Enumerable.Reference':'__impl__'/1
  'Elixir.Enumerable.Tuple':'__impl__'/1
  'Elixir.Hex':start/0
  'Elixir.Hex':version/0
  'Elixir.List.Chars.Function':'__impl__'/1
  'Elixir.List.Chars.Map':'__impl__'/1
  'Elixir.List.Chars.PID':'__impl__'/1
  'Elixir.List.Chars.Port':'__impl__'/1
  'Elixir.List.Chars.Reference':'__impl__'/1
  'Elixir.List.Chars.Tuple':'__impl__'/1
  'Elixir.Logger':add_backend/2
  'Elixir.Logger':configure/1
  'Elixir.Logger':flush/0
  'Elixir.Logger':remove_backend/1
  'Elixir.Logger.App':start/0
  'Elixir.Logger.App':stop/0
  'Elixir.String.Chars.Function':'__impl__'/1
  'Elixir.String.Chars.Map':'__impl__'/1
  'Elixir.String.Chars.PID':'__impl__'/1
  'Elixir.String.Chars.Port':'__impl__'/1
  'Elixir.String.Chars.Reference':'__impl__'/1
  'Elixir.String.Chars.Tuple':'__impl__'/1
  asn1rt_nif:decode_ber_tlv/1
  asn1rt_nif:encode_ber_tlv/1
  compile:file/2
  compile:forms/2
  compile:noenv_forms/2
  compile:output_generated/1
  cover:analyse_to_file/3
  cover:compile_beam_directory/1
  cover:modules/0
  cover:start/0
  fprof:analyse/1
  fprof:apply/3
  fprof:profile/1
  httpc:request/5
  httpc:set_options/2
  inets:start/2
  inets:stop/2
  leex:file/2
  yecc:file/2
Unknown types:
  compile:option/0
 done in 3m15.55s
done (passed successfully)

```
Then I ran `mix dialyzer` on dialyxir:
```
notroot@6c086fe12b82:/work$ mix dialyzer
Starting Dialyzer
dialyzer --no_check_plt --plt /home/notroot/.dialyxir_core_18_1.1.1.plt -Wunmatched_returns -Werror_handling -Wrace_conditions -Wunderspecs /work/_build/dev/lib/dialyxir/ebin
  Proceeding with analysis...
dialyzer.plt.ex:65: Guard test is_binary(_@4::string()) can never succeed
dialyzer.plt.ex:84: Guard test 'or'('false','false') can never succeed
Unknown functions:
  dialyzer:plt_info/1
 done in 0m1.50s
done (warnings were emitted)

```
Seems to be working but I am not sure if I should interpret the output as a 100% success...

**Comment by jeremyjh** [comment] 2015-12-30 17:13
@sdwolf Yes that is successful output - you are analyzing Dialyxir itself and there are a couple of warnings, those have been fixed in version 0.2.9. The :dialyzer module is not added to the PLT by default as it is not likely to be used in an application.

I'm closing this issue as the root cause here is running an Erlang version 18 dialyzer on an Elixir built with  Erlang 17. If you are seeing this issue you will need to rebuild Elixir from source using Erlang 18.

**Closed by jeremyjh** 2015-12-30 17:13 UTC

**Comment by candeira** [comment] 2016-01-05 04:03
Just a heads-up.I was using the Erlang Solutions-built Elixir, I got this same error. So it appears that their erlang is E18, but their Elixir is built with E17 too.

**Comment by matteosister** [comment] 2016-04-11 17:14
same here! erlang solution repo and the error showed up. /cc @candeira

**Comment by rmarscher** [comment] 2017-03-23 15:41
Sorry to comment on an old issue, but I hit this problem due to an existing empty plt file. I don't see anyone here mentioning checking for existing plt files and deleting them. This was for a project still on dialyxer 0.3.5. Deleting the existing plt file and running again got it to work.

The error output looks like this:
```
# mix dialyzer.plt
Checking PLT for missing apps.
** (FunctionClauseError) no function clause matching in Keyword.get/3
    (elixir) lib/keyword.ex:150: Keyword.get(:not_valid, :files, nil)
    lib/mix/tasks/dialyzer.plt.ex:163: Mix.Tasks.Dialyzer.Plt.core_plt_contains?/2
    lib/mix/tasks/dialyzer.plt.ex:154: anonymous fn/1 in Mix.Tasks.Dialyzer.Plt.missing_apps/0
    (elixir) lib/enum.ex:787: anonymous fn/3 in Enum.filter/2
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:787: Enum.filter/2
    lib/mix/tasks/dialyzer.plt.ex:144: Mix.Tasks.Dialyzer.Plt.need_add?/0
    lib/mix/tasks/dialyzer.plt.ex:56: Mix.Tasks.Dialyzer.Plt.run/1
```
