### ISSUE TITLE
Failure to parse warning

### ISSUE THREAD

**Issue by erikreedstrom** [jeremyjh/dialyxir#167] opened 2018-06-06 20:08 UTC
Failed to parse warning:
`[{:"(", 1}, {:variable_alias, 1, 'Ventity_class@1::any(),Ventity_id@1::any(),fun((_,_) -> \'nil\' | {\#{\'__struct__\':=\'Elixir.Multipass.Message\', \'causation_id\':=\'nil\' | <<_:208>>, \'change_type\':=\'create\' | \'delete\' | \'update\', \'correlation_id\':=\'nil\' | binary(), \'entity_class\':=binary(), \'entity_id\':=binary(), \'event_id\':=<<_:208>>, \'meta\':=map(), \'payload\':=map(), \'source\':=\'nil\' | binary(), \'target\':=\'nil\' | binary(), \'timestamp\':=\'nil\' | binary()},[binary()],\#{\'__struct__\':=\'Elixir.DateTime\', \'calendar\':=atom(), \'day\':=integer(), \'hour\':=integer(), \'microsecond\':={_,_}, \'minute\':=integer(), \'month\':=integer(), \'second\':=integer(), \'std_offset\':=integer(), \'time_zone\':=binary(), \'utc_offset\':=integer(), \'year\':=integer(), \'zone_abbr\':=binary()}}),Vopts@3'}, {:::, 1}, {:"[", 1}, {:"{", 1}, {:atom_part, 1, 'a'}, {:atom_part, 1, 't'}, {:atom_part, 1, 'o'}, {:atom_part, 1, 'm'}, {:"(", 1}, {:")", 1}, {:",", 1}, {:_, 1}, {:"}", 1}, {:"]", 1}, {:")", 1}]`

Legacy warning:
`apps/multipass/lib/multipass/outbound/outbound.ex:62: The call 'Elixir.CoreAPI.Encoder':encode_change_event(Ventity_class@1::any(),Ventity_id@1::any(),fun((_,_) -> 'nil' | {#{'__struct__':='Elixir.Multipass.Message', 'causation_id':='nil' | <<_:208>>, 'change_type':='create' | 'delete' | 'update', 'correlation_id':='nil' | binary(), 'entity_class':=binary(), 'entity_id':=binary(), 'event_id':=<<_:208>>, 'meta':=map(), 'payload':=map(), 'source':='nil' | binary(), 'target':='nil' | binary(), 'timestamp':='nil' | binary()},[binary()],#{'__struct__':='Elixir.DateTime', 'calendar':=atom(), 'day':=integer(), 'hour':=integer(), 'microsecond':={_,_}, 'minute':=integer(), 'month':=integer(), 'second':=integer(), 'std_offset':=integer(), 'time_zone':=binary(), 'utc_offset':=integer(), 'year':=integer(), 'zone_abbr':=binary()}}),Vopts@3::[{atom(),_}]) breaks the contract ('Elixir.String':t(),'Elixir.String':t(),projector(),elixir:keyword()) -> {'ok',[map()],['Elixir.String':t()]} | {'error',any()}`

**Comment by asummers** [comment] 2018-06-06 20:17
Thank you for the report! This is the same underlying issue as #165 and will be fixed with that work. I'll be sure to add a test for your input to make sure there's not something else funky happening there.

**Comment by asummers** [comment] 2018-06-06 20:17
Duplicate of #165

**Closed by asummers** 2018-06-06 20:17 UTC
