### ISSUE TITLE
Plt not begin created with the new 0.4

### ISSUE THREAD

**Issue by olafura** [jeremyjh/dialyxir#56] opened 2016-11-24 14:58 UTC
I'm getting:
dialyzer: No such file, directory or application "(redacted)/_build/dev/dialyxir_erlang-19.1_elixir-1.3.4_deps-dev.plt"

I would usually do mix dialyzer.plt but it does not exist anymore as far as I can tell.

**Comment by jeremyjh** [comment] 2016-11-24 17:48
Are you running with --no-check ? Otherwise it would create the PLT.

**Comment by olafura** [comment] 2016-11-25 15:06
Hi sorry but it was a config problem on our end ;)

**Comment by jeffutter** [comment] 2016-12-03 23:21
@olafura can you relay what your config problem was? I just installed dialyxir and am running into the same problem

**Comment by jeremyjh** [comment] 2016-12-04 02:50
@jeffutter  do you have any keys at all in your project config for dialyzer? Can you paste those as well as the command output when you run `mix dialyzer` ?

**Comment by olafura** [comment] 2016-12-04 19:35
So we are using a umbrella project and had this in the sub projects:
`dialyzer: [plt_add_deps: :transitive],`

So running `mix dialyzer` in sub project doesn't work to create the plt.

I would have to do more tests to see if it's these specific settings or
just umbrella projects.

**Comment by jeremyjh** [comment] 2016-12-04 19:41
Ah, this is a bug. You need to run in parent to create the PLT right now I
just realized.

I can't calculate dependencies when you run in a child due to load order
conflicts - so I just don't check if it's up to date. I need to check if
the file is there though.

**Comment by jeffutter** [comment] 2016-12-05 00:38
Ahh yes. I was doing this in a nerves umbrella project. In nerves umbrella projects, you build nerves (for now) from the apps/fw applications - at least until distillery is implemented instead of exrm. So I was trying to build from there. I moved it out to the main app and got much further, but now I"m getting: 

```
** (throw) {:dialyzer_error, [67, 111, 117, 108, 100, 32, 110, 111, 116, 32, 103, 101, 116, 32, 97, 98, 115, 116, 114, 97, 99, 116, 32, 99, 111, 100, 101, 32, 102, 111, 114, 32, 102, 105, 108, 101, 58, 32, '/Users/jeff.utter/Projects/temp-relay/_build/dev/lib/jsx/ebin/jsx.beam', 32, 40, 112, 108, 101, 97, 115, 101, 32, 114, ...]}
    dialyzer_plt.erl:469: :dialyzer_plt.compute_md5_from_file/1
    dialyzer_plt.erl:436: :dialyzer_plt.compute_new_md5_1/3
...
```

**Comment by jeremyjh** [comment] 2016-12-05 11:44
Can you paste the entire command output please?

**Comment by jeremyjh** [comment] 2016-12-08 03:46
@jeffutter I agree it is a separate issue; I believe it means the jsx.beam file was not compiled with debug_info. If you paste that list into `iex` you'll see the binary formatted as "Could not get abstract code for: '/Users/jeff.utter/Projects/temp-relay/_build/dev/lib/jsx/ebin/jsx.beam' ... the rest is truncated but is probably "Recompile with +debug_info or analyze starting from source code". 

On OSX you may need to build Elixir with debug info enabled, see (https://github.com/jeremyjh/dialyxir/issues/42).

Please confirm if that works for you because I need to update the README and should probably try to get this fixed in Homebrew; other OS distributions are building with that option already.

**Comment by jeremyjh** [comment] 2016-12-08 03:51
I guess I should read the whole issue I link to! That wasn't a brew package issue at all but specific to Elixir 1.2.2. I would not imagine you are not using that version though yeah?

**Comment by cranberyxl** [comment] 2016-12-12 23:05
I've got the same error showing up for `jsx.beam` on osx. I've tried using both asdf and brew versions of elixir 1.3.4.

**Comment by jeremyjh** [comment] 2016-12-13 03:56
@cranberyxl I cannot recreate this on Arch using either the community package or a build of Elixir from source. 

This is what I'm trying to recreate it:

```shell
git clone https://github.com/talentdeficit/jsx.git
cd jsx
mix do deps.get, compile, dialyzer
```

**Comment by cranberyxl** [comment] 2016-12-13 04:48
@jeremyjh I can reproduce it on this repo: https://github.com/talentdeficit/exjsx 

Erlang 19.1
Elixir 1.3.4
OSX 10.11.6

**Comment by jeremyjh** [comment] 2016-12-13 05:02
Ah ok, I can reproduce with that as well, thanks. The problem happens when trying to add the jsx.beam to the PLT.

**Comment by cranberyxl** [comment] 2016-12-13 15:22
@jeremyjh Thank you! 🎉

**Closed** 2017-01-08 03:13 UTC
Labels: bug

**Comment by jeremyjh** [comment] 2017-01-08 03:17
@jeffutter  your original issue (umbrella child doesn't build PLT) is fixed in 0.4.3 on hex now.

**Comment by romenigld** [comment] 2017-08-24 18:36
I was trying this:
```
mix archive.build
Generated archive "dialyxir-0.5.1.ez" with MIX_ENV=dev
MacBook-Pro-de-Romenig:dialyxir romenigld$ mix archive.install
Found existing archive: /Users/romenigld/.mix/archives/dialyxir-0.5.1.
Are you sure you want to replace it with "dialyxir-0.5.1.ez"? [Yn] Y
* creating /Users/romenigld/.mix/archives/dialyxir-0.5.1
MacBook-Pro-de-Romenig:dialyxir romenigld$ mix archive.install
Found existing archive: /Users/romenigld/.mix/archives/dialyxir-0.5.1.
Are you sure you want to replace it with "dialyxir-0.5.1.ez"? [Yn] Y
* creating /Users/romenigld/.mix/archives/dialyxir-0.5.1
MacBook-Pro-de-Romenig:dialyxir romenigld$ mix dialyzer.plt
** (Mix) The task "dialyzer.plt" could not be found. Did you mean "dialyzer"?
```
So I'm searching on internet and watched for do this:
```
MacBook-Pro-de-Romenig:dialyxir romenigld$ mix dialyzer
Checking PLT...
[:dialyzer, :elixir, :kernel, :mix, :stdlib]
Finding suitable PLTs
Looking up modules in dialyxir_erlang-20.0_elixir-1.4.5_deps-dev.plt
Looking up modules in dialyxir_erlang-20.0_elixir-1.4.5.plt
Looking up modules in dialyxir_erlang-20.0.plt
Finding applications for dialyxir_erlang-20.0.plt
Finding modules for dialyxir_erlang-20.0.plt
Creating dialyxir_erlang-20.0.plt
Looking up modules in dialyxir_erlang-20.0.plt
Removing 3 modules from dialyxir_erlang-20.0.plt
Checking 11 modules in dialyxir_erlang-20.0.plt
Adding 152 modules to dialyxir_erlang-20.0.plt
Finding applications for dialyxir_erlang-20.0_elixir-1.4.5.plt
Finding modules for dialyxir_erlang-20.0_elixir-1.4.5.plt
Copying dialyxir_erlang-20.0.plt to dialyxir_erlang-20.0_elixir-1.4.5.plt
Looking up modules in dialyxir_erlang-20.0_elixir-1.4.5.plt
Checking 163 modules in dialyxir_erlang-20.0_elixir-1.4.5.plt
Adding 220 modules to dialyxir_erlang-20.0_elixir-1.4.5.plt
Finding applications for dialyxir_erlang-20.0_elixir-1.4.5_deps-dev.plt
Finding modules for dialyxir_erlang-20.0_elixir-1.4.5_deps-dev.plt
Copying dialyxir_erlang-20.0_elixir-1.4.5.plt to dialyxir_erlang-20.0_elixir-1.4.5_deps-dev.plt
Looking up modules in dialyxir_erlang-20.0_elixir-1.4.5_deps-dev.plt
Checking 383 modules in dialyxir_erlang-20.0_elixir-1.4.5_deps-dev.plt
Adding 109 modules to dialyxir_erlang-20.0_elixir-1.4.5_deps-dev.plt
Starting Dialyzer
dialyzer args: [check_plt: false,
 init_plt: '/Users/romenigld/elixir_workspace/introduction_elixie_2nd_ed/ch02/ex1-drop/dialyxir/_build/dev/dialyxir_erlang-20.0_elixir-1.4.5_deps-dev.plt',
 files_rec: ['/Users/romenigld/elixir_workspace/introduction_elixie_2nd_ed/ch02/ex1-drop/dialyxir/_build/dev/lib/dialyxir/ebin'],
 warnings: [:unmatched_returns, :error_handling, :underspecs, :unknown]]
done in 0m1.65s
done (passed successfully)
MacBook-Pro-de-Romenig:dialyxir romenigld$
```
But when try again this command underneath, that builds a Persistent Lookup Table (PLT) that stores results of Dialyzer analyses don't work's!
```
 romenigld$ mix dialyzer.plt
** (Mix) The task "dialyzer.plt" could not be found. Did you mean "dialyzer"?
```
Can anyone help me with this?

**Comment by jeremyjh** [comment] 2017-08-24 18:38
@romenigld just like the error says there is no task called `dialyzer.plt`. All you need to do is run `mix dialyzer`. The output you pasted from that is what is expected and is working correctly.

**Comment by romenigld** [comment] 2017-08-24 22:14
Hello @jeremyjh, so  I was seeking on internet and I do this for install and so I do the this mix with flag --plt like:
`mix dialyzer --plt
`
and work's thank's!
