### ISSUE TITLE
Failed to parse error message

### ISSUE THREAD

**Issue by adkron** [jeremyjh/dialyxir#253] opened 2018-10-05 22:06 UTC
Failed to parse warning:
[{:"(", 1}, {:atom_part, 1, 'K'}, {:atom_part, 1, 'e'}, {:atom_part, 1, 'y'}, {:",", 1}, {:atom_part, 1, 'M'}, {:atom_part, 1, 'a'}, {:atom_part, 1, 'p'}, {:int, 1, 1}, {:")", 1}, {:->, 1}, {:atom_part, 1, 'M'}, {:atom_part, 1, 'a'}, {:atom_part, 1, 'p'}, {:int, 1, 2}, 
{:atom_part, 1, 'w'}, {:atom_part, 1, 'h'}, {:atom_part, 1, 'e'}, {:atom_part, 1, 'n'}, {:atom_part, 1, 'K'}, {:atom_part, 1, 'e'}, {:atom_part, 1, 'y'}, {:::, 1}, {:atom_part, 1, 't'}, {:atom_part, 1, 'e'}, {:atom_part, 1, 'r'}, {:atom_part, 1, 'm'}, {:"(", 1}, {:")", 
1}, {:",", 1}, {:atom_part, 1, 'M'}, {:atom_part, 1, 'a'}, {:atom_part, 1, 'p'}, {:int, 1, 1}, {:::, 1}, {:atom_part, 1, 'm'}, {:atom_part, 1, 'a'}, {:atom_part, 1, 'p'}, {:"(", 1}, {:")", 1}, {:",", 1}, {:atom_part, 1, 'M'}, {:atom_part, 1, 'a'}, {:atom_part, 1, 'p'}, 
{:int, 1, 2}, {:::, 1}, {:atom_part, 1, 'm'}, {:atom_part, 1, ...}, {:atom_part, ...}, {...}, ...]

Legacy warning:
lib/user_manager.ex:402: The call maps:remove('current_password',Vuser_item@1::{'error',_}) breaks the contract (Key,Map1) -> Map2 when Key :: term(), Map1 :: map(), Map2 :: map()

**Comment by AndrewDryga** [comment] 2018-10-08 13:10
I got similar one:
```
Failed to parse warning:
[{:"(", 1}, {:atom_part, 1, 'T'}, {:atom_part, 1, 'i'}, {:atom_part, 1, 'm'}, {:atom_part, 1, 'e'}, {:atom_part, 1, 'r'}, {
:atom_part, 1, 'R'}, {:atom_part, 1, 'e'}, {:atom_part, 1, 'f'}, {:")", 1}, {:->, 1}, {:atom_part, 1, 'R'}, {:atom_part, 1,
 'e'}, {:atom_part, 1, 's'}, {:atom_part, 1, 'u'}, {:atom_part, 1, 'l'}, {:atom_part, 1, 't'}, {:atom_part, 1, 'w'}, {:atom
_part, 1, 'h'}, {:atom_part, 1, 'e'}, {:atom_part, 1, 'n'}, {:atom_part, 1, 'T'}, {:atom_part, 1, 'i'}, {:atom_part, 1, 'm'
}, {:atom_part, 1, 'e'}, {:atom_part, 1, 'r'}, {:atom_part, 1, 'R'}, {:atom_part, 1, 'e'}, {:atom_part, 1, 'f'}, {:::, 1},
{:atom_part, 1, 'r'}, {:atom_part, 1, 'e'}, {:atom_part, 1, 'f'}, {:atom_part, 1, 'e'}, {:atom_part, 1, 'r'}, {:atom_part,
1, 'e'}, {:atom_part, 1, 'n'}, {:atom_part, 1, 'c'}, {:atom_part, 1, 'e'}, {:"(", 1}, {:")", 1}, {:",", 1}, {:atom_part, 1,
 'T'}, {:atom_part, 1, 'i'}, {:atom_part, 1, 'm'}, {:atom_part, 1, 'e'}, {:::, 1}, {:atom_part, 1, ...}, {:atom_part, ...},
 {...}, ...]


Legacy warning:
apps/talkinto_domain/lib/talkinto_domain/task_queue.ex:350: The call erlang:cancel_timer(_timer_ref@1::'false') breaks the
contract (TimerRef) -> Result when TimerRef :: reference(), Time :: non_neg_integer(), Result :: Time | 'false'
```

**Comment by asummers** [comment] 2018-10-23 01:36
The issue here is that `when` clauses in Erlex are unprepared for multiple clauses. Will track and try to get a fix out.

**Comment by asummers** [comment] 2018-10-23 01:40
Jumped the gun on last comment. I _think_ what's happening here is that it's not parsing Erlang terms appropriately? 

Thank you both for the reports.

**Comment by asummers** [comment] 2018-10-23 01:48
I actually can't reproduce either of these, locally. What versions of Erlex and Dialyxir are you running?

**Comment by jeremyjh** [comment] 2018-11-01 00:38
Can you reproduce this on rc.4 ?

`
  {:dialyxir, "~> 1.0.0-rc.4", only: [:dev], runtime: false}
`

**Comment by AndrewDryga** [comment] 2018-11-01 10:32
@asummers 
```
elixir -v
Erlang/OTP 21 [erts-10.0.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.7.2 (compiled with Erlang/OTP 21)
```

@jeremyjh just updated to master branch and it still reporoduces..

**Comment by asummers** [comment] 2018-11-07 05:30
@AndrewDryga @adkron do either of you have a public branch, or a small example I can play with that exhibits this?

**Comment by adkron** [comment] 2018-11-07 18:42
I don’t have anything public. When I get to a computer I can take a look and see if I can put together a minimum example. 

Amos King
Binary Noggin

**Comment by asummers** [comment] 2018-12-28 17:03
I believe this is resolved in Erlex master. A `mix deps.update erlex` on `rc4` or later should give you code to fix this. Please feel free to reopen/make a new issue if that is incorrect!

**Closed by asummers** 2018-12-28 17:03 UTC
Labels: bug
