### ISSUE TITLE
not sure if I'm supposed to do a bug report here?

### ISSUE THREAD

**Issue by isaac-rstor** [jeremyjh/dialyxir#180] opened 2018-06-09 01:46 UTC
Two new bugs?

encountered during a major refactor going from error tuples to error atom tuples...

Please file a bug in https://github.com/jeremyjh/dialyxir/issues with this message.

Failed to format warning:
"@spec a({:error, erratom@1, Vtxt}) :: :ok\ndef a() do\n  :ok\nend\n"

Legacy warning:
lib/fumsched/serverless.ex:54: The pattern {'error', Verratom@1, Vtxt@1} can never match the type {'error',<<_:344>>}

Please file a bug in https://github.com/jeremyjh/dialyxir/issues with this message.

Failed to format warning:
"@spec a({:error, erratom@1, Vtxt}) :: :ok\ndef a() do\n  :ok\nend\n"

Legacy warning:
lib/fumsched/serverless.ex:54: The pattern {'error', Verratom@1, Vtxt@1} can never match the type 'error'

**Comment by asummers** [comment] 2018-06-09 05:41
Thank you for the reports! This is a duplicate of #165. I hope to knock that out this weekend.

**Closed** 2018-06-09 05:41 UTC
